### ISSUE TITLE
Question, support android kotlin?

### ISSUE THREAD

**Issue by JhonnySalles** [Ifropc/Kotomo#1]
Good evening, I would just like to know if different from the original project that does not support running on android, as it does not have some imageio libraries. This project support android kotlin?

**Comment by Ifropc** [comment]
Hi @JhonnySalles !
Thank you for taking interest in the project.

I think there should be no problem using this library on Android. I have some dependencies, but they are ether pure kotlin (common module) or pure java (jvm module)
You can see the dependencies list here https://github.com/Ifropc/Kotomo/blob/695b67066bfdae0d1135a5ad66b9517fdf4fcf39/build.gradle.kts#L46

If you don't mind waiting, I can upload maven artifacts later this week for you to try it out (either today or Wednesday/Thursday)

FYI: the library itself is almost untouched compared to the original project, but I made some major changes here and there.
For example, I completely removed dictionary support. 
Please let me know if you need it, I'll consider restoring it for the JVM implementation.
(This feature allows to look up OCR results in JMDict. I believe this specific functionality is most likely implemented by some third library)

**Comment by Ifropc** [comment]
@JhonnySalles I didn't have time to setup maven central deploy, you can use this [pre-release](https://github.com/Ifropc/Kotomo/releases/tag/0.0.1-SNAPSHOT)
(I also haven't sorted out local changes, so it's slightly different from remote. Up to date sources are included)
Please extract it in ` ~/.m2/repository/io/github/ifropc/kotomo ` 
Example of usage is here
https://github.com/Ifropc/kotomo-examples/blob/master/src/main/kotlin/Main.kt
This code runs OCR on image 1.jpg on point with coordinates [0, 0]

If you want to load image from memory simply wrap it to KotomoImage
```val image = KotomoImageImpl(bufferedImage)```

**Comment by Ifropc** [comment]
@JhonnySalles 
I provided a maven package, it's available in the maven central (`io.github.ifropc.kotomo:kotomo-jvm:0.1`)
You can see example of usages here
https://github.com/Ifropc/kotomo-examples
This code runs OCR on image 1.jpg on point with coordinates [0, 0]

I'll close the issue for now. If you have any troubles with using the library, please feel free to open new issue.

**Comment by JhonnySalles** [comment]
Thank you very much for all the work, I have a manga reader in which I have already implemented tesseract and google vision, and I still need to add the kanji recognition. The kotomo at first did not work on android, but I will test your library.
Thanks again.
